data:
  num_classes: 7
  train: 'dataset/meta/train'
  test: 'dataset/meta/test'
  file_format: '*.file_extension'
---
train:
  num_workers: 16
  batch_size: 64
  optimizer: 'adam'
  adam:
    initlr: 0.0003
    lrdecay:
      epoch: 36
      gamma: 0.1
---
test:
  num_workers: 16
  batch_size: 64
---
model:

---
log:
  summary_interval: 1
  chkpt_interval: 10
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
